In [1]:
import numpy as np 

## section- **1**

###  check if elements from following arrays return the logical value True.

In [7]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])


C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

>use all() method

In [8]:
np.all(A)

True

In [9]:
np.all(B)

False

In [10]:
np.all(C)

False

In [11]:
np.all(D)

True

### check if all elements from the following arrays returns the logical value True along the axis 1

In [3]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

In [4]:
np.all(A,axis=1)

array([ True,  True])

In [5]:
np.all(B,axis=1)

array([ True, False])

In [6]:
np.all(C,axis=1)

array([False,  True])

### check if any elements in the following arrays return the logical value True

In [12]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

>use any() method

In [13]:
np.any(A)

False

In [14]:
np.any(B)

True

In [15]:
np.any(C)

True

In [16]:
np.any(D)

True

### check if any elements in the following arrays return the logical value True along axis 0

In [17]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

In [18]:
np.any(A,axis=0)

array([False, False, False])

In [19]:
np.any(B,axis=0)

array([False,  True, False])

In [20]:
np.any(C,axis=0)

array([ True, False, False])

In [21]:
np.any(D,axis=0)

array([ True, False])

### check if the following array has missing data

In [22]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

>use isnan() method

In [24]:
sum=np.sum(A)
np.isnan(sum)

True

### check if following arrays are equal(element wise)

In [25]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

> use allclose() method

In [27]:
np.allclose(A,B)

True

### check the following arrays are equal(element wise)

In [28]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

> use ==

In [29]:
A==B

array([False, False,  True])

> using equal() method

In [30]:

np.equal(A,B)

array([False, False,  True])

### check which numbers from the first array is greater than the elements from second array and print 

In [31]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

> using >

In [32]:
A>B

array([ True, False, False, False])

> using greater() method

In [33]:
np.greater(A,B)

array([ True, False, False, False])

### create a 4x4 array of zeroes and print 

> use zeros() method

In [36]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### create a 10x10 array filled with 255, set datatype to float and print

> using ones() method

In [38]:
np.ones([10,10],dtype=float)*255

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

>using full() method

In [39]:
np.full([10,10],dtype=float,fill_value=255)

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

## section- **2**

### using numpy create a one dimensional array of all two digit numbers and print this array to the console.

>use arange() method

In [40]:
np.arange(10,100,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### using numpy, create the following array

>[[10 11 12 13 14 15 16 17 18 19]  
 [20 21 22 23 24 25 26 27 28 29]  
 [30 31 32 33 34 35 36 37 38 39]  
 [40 41 42 43 44 45 46 47 48 49]  
 [50 51 52 53 54 55 56 57 58 59]  
 [60 61 62 63 64 65 66 67 68 69]  
 [70 71 72 73 74 75 76 77 78 79]  
 [80 81 82 83 84 85 86 87 88 89]  
 [90 91 92 93 94 95 96 97 98 99]]

In [41]:
np.arange(10,100,1).reshape(9,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### using nupy create a 6x6 two dimensional array-identity matrix with int datatype and print to the console

>use eye() or identity()

In [42]:
np.eye(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [47]:
np.eye(6,6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [45]:
np.identity(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### set the random seed to 10, then using numpy create a one dimensional array consisting of 30 pseudo randomly generated values from the uniform distribution(0,1),print result to the console

>use rand() method

In [48]:
np.random.seed(10)

In [49]:
result=np.random.rand(30)

In [50]:
result

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])

### using numpy create a two dimensional array with the shape (10,4) pseudo-randomly generated values from the standard normal distribution N(0,1).set the random seed to 20,print result to screen.

>use randn() method

In [51]:
np.random.seed(20)

In [53]:
1*np.random.randn(10,4)+0

array([[-3.38490605e-01,  3.20970784e-01, -6.02308018e-01,
         1.54472836e+00],
       [ 6.47034084e-01,  5.93217213e-01,  4.38024497e-01,
         1.35778902e+00],
       [ 1.20451128e+00,  1.35179619e+00,  4.93437236e-01,
        -2.70436525e+00],
       [-5.55185797e-01,  1.50856026e-03,  8.57093817e-01,
         1.48114365e+00],
       [-2.19661122e-01,  1.50339816e+00, -1.48238505e+00,
        -8.56164218e-01],
       [-8.28692770e-01,  1.14047603e-01,  5.27728470e-01,
         1.55838222e-01],
       [ 1.30142940e+00, -9.94801908e-01,  2.09466534e+00,
         3.59428994e-01],
       [ 6.91002119e-01, -1.48571961e+00,  9.87886147e-02,
        -2.28321031e-01],
       [-8.54775487e-01, -5.13145106e-01, -9.62215984e-01,
        -4.82450911e-01],
       [-2.39469757e-01,  4.59744227e-01,  6.46430166e-01,
         4.87402961e-01]])