 (  SHARED on 24/11/2021- DHARNA AHUJA)


>1.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.


In [1]:
import numpy as np
arr1=np.array([20,60,89,76,87])
arr2=np.array([87,89])

In [2]:
ispres=np.in1d(arr1,arr2)
ispres

array([False, False,  True, False,  True])

>2.Write a NumPy program to find common values between two arrays.


In [3]:
np.intersect1d(arr1,arr2)

array([87, 89])

>3.Write a NumPy program to Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive.


In [4]:
np.linspace(2.5,6.5,30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

>4. Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.

Expected Output:
Original array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]


In [8]:
orgarr=np.arange(1,15)
orgarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.split(orgarr,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]